export interface ArquetipoCompleto {
  tipo: string
  nome: string
  subtitulo: string
  descricao: string
  categoria: 'analistas' | 'diplomatas' | 'sentinelas' | 'exploradores'
  cor: string
  icone: string
  famosos: string[]
  pontosFortes: string[]
  pontosFracos: string[]
  comoTrabalha: string[]
  comoComunica: string
  fraseChave: string
}

export const COR_CATEGORIA = {
  analistas: '#9747FF',
  diplomatas: '#14AE5C',
  sentinelas: '#4A90D9',
  exploradores: '#FF8C00',
} as const

export const CATEGORIA_NOMES: Record<string, string> = {
  analistas: 'Analistas',
  diplomatas: 'Diplomatas',
  sentinelas: 'Sentinelas',
  exploradores: 'Exploradores',
}

export const CATEGORIA_DESC: Record<string, string> = {
  analistas: 'Intuitivo e Analitico — racionalidade, imparcialidade e excelencia intelectual',
  diplomatas: 'Intuitivo e Emocional — empatia, talento diplomatico e forte idealismo',
  sentinelas: 'Realista e Planejador — praticidade, foco em ordem, seguranca e estabilidade',
  exploradores: 'Realista e Desbravador — espontaneidade, engenhosidade e flexibilidade',
}

export const ARQUETIPOS: Record<string, ArquetipoCompleto> = {
  INTJ: {
    tipo: 'INTJ',
    nome: 'O Showrunner',
    subtitulo: 'Estrategista criativo que enxerga o projeto completo',
    descricao: 'Mente estrategica que enxerga o projeto completo antes de qualquer claquete. Planeja cada detalhe com visao macro e executa com precisao cirurgica. Onde outros veem caos, voce ve um plano. Sua capacidade de antecipar problemas e encontrar solucoes elegantes faz de voce o tipo de profissional que transforma ideias ambiciosas em realidade.',
    categoria: 'analistas',
    cor: '#9747FF',
    icone: '🎬',
    famosos: ['Christopher Nolan', 'Stanley Kubrick', 'David Fincher', 'James Cameron'],
    pontosFortes: [
      'Visao estrategica de longo prazo',
      'Capacidade de planejar projetos complexos',
      'Resolve problemas antes deles acontecerem',
      'Alto padrao de qualidade',
      'Independente e auto-motivado',
    ],
    pontosFracos: [
      'Pode parecer distante ou frio com a equipe',
      'Dificuldade em aceitar ideias que fogem do plano',
      'Perfeccionismo pode atrasar entregas',
      'Pode ignorar o lado emocional das decisoes',
    ],
    comoTrabalha: [
      'Precisa de autonomia e espaco pra pensar',
      'Rende mais com briefings claros e objetivos',
      'Prefere poucos projetos com profundidade',
      'Trabalha melhor com deadlines firmes mas razoaveis',
    ],
    comoComunica: 'Direto e objetivo. Prefere comunicacao escrita e estruturada. Evite rodeios — va direto ao ponto com dados e fatos.',
    fraseChave: '"Vamos pensar isso direito antes de executar."',
  },
  INTP: {
    tipo: 'INTP',
    nome: 'O Tecnico Visionario',
    subtitulo: 'Resolve qualquer problema com criatividade tecnica',
    descricao: 'Resolve qualquer problema tecnico com criatividade. Vive explorando novos softwares, plugins e workflows. Quando a equipe trava, voce descobre um caminho que ninguem pensou. Sua curiosidade insaciavel e sua capacidade de conectar conceitos aparentemente desconectados fazem de voce o recurso mais valioso em projetos que exigem inovacao tecnica.',
    categoria: 'analistas',
    cor: '#9747FF',
    icone: '🔧',
    famosos: ['Hideo Kojima', 'George Lucas (tech)', 'Wachowski Sisters', 'Denis Villeneuve'],
    pontosFortes: [
      'Resolucao criativa de problemas tecnicos',
      'Aprende qualquer ferramenta rapidamente',
      'Pensamento lateral — acha solucoes inesperadas',
      'Curiosidade natural por inovacao',
      'Excelente em otimizar workflows',
    ],
    pontosFracos: [
      'Pode se perder em detalhes tecnicos',
      'Dificuldade em estimar tempo de entrega',
      'As vezes reinventa a roda desnecessariamente',
      'Pode parecer desligado em reunioes',
    ],
    comoTrabalha: [
      'Precisa de liberdade pra explorar solucoes',
      'Rende mais quando o problema e desafiador',
      'Prefere trabalhar no proprio ritmo',
      'Se motiva com problemas novos, nao com rotina',
    ],
    comoComunica: 'Tecnico e detalhista. Gosta de explicar o "como" e o "por que". Tenha paciencia — as melhores ideias dele precisam de tempo pra amadurecer.',
    fraseChave: '"E se a gente fizer de um jeito diferente?"',
  },
  ENTJ: {
    tipo: 'ENTJ',
    nome: 'O Diretor',
    subtitulo: 'Lidera a visao criativa com clareza e determinacao',
    descricao: 'Lidera a visao criativa com mao firme e clareza. Sabe o que quer, comunica com precisao e inspira a equipe a entregar o melhor. Nasce pra comandar sets e projetos ambiciosos. Sua confianca natural e capacidade de tomar decisoes rapidas sob pressao fazem de voce o lider que toda producao precisa nos momentos criticos.',
    categoria: 'analistas',
    cor: '#9747FF',
    icone: '🎯',
    famosos: ['Ridley Scott', 'Michael Bay', 'Kathryn Bigelow', 'Martin Scorsese'],
    pontosFortes: [
      'Lideranca natural e carismatica',
      'Tomada de decisao rapida e assertiva',
      'Comunica a visao com clareza',
      'Motiva a equipe a dar o melhor',
      'Excelente em gerenciar multiplos projetos',
    ],
    pontosFracos: [
      'Pode ser autoritario demais',
      'Impaciente com processos lentos',
      'Dificuldade em delegar sem microgerenciar',
      'Pode atropelar sentimentos da equipe',
    ],
    comoTrabalha: [
      'Precisa estar no comando ou ter voz ativa',
      'Rende mais com desafios grandes e ambiciosos',
      'Prefere velocidade a perfeccao',
      'Se motiva com resultados visiveis',
    ],
    comoComunica: 'Assertivo e energico. Gosta de reunioes rapidas e decisivas. Apresente opcoes, nao problemas — ele quer solucoes.',
    fraseChave: '"Vamos fazer acontecer. Agora."',
  },
  ENTP: {
    tipo: 'ENTP',
    nome: 'O Roteirista Provocador',
    subtitulo: 'Ideias disruptivas que transformam briefings em conceitos',
    descricao: 'Ideias disruptivas sao sua materia-prima. Questiona tudo, propoe angulos inesperados e transforma briefings simples em conceitos memoraveis. O caos criativo e seu habitat natural. Sua capacidade de ver conexoes que ninguem ve e defender ideias ousadas faz de voce a faisca que acende os melhores projetos da produtora.',
    categoria: 'analistas',
    cor: '#9747FF',
    icone: '✍️',
    famosos: ['Quentin Tarantino', 'Charlie Kaufman', 'Spike Jonze', 'Edgar Wright'],
    pontosFortes: [
      'Criatividade inesgotavel',
      'Excelente em brainstorms e pitching',
      'Questiona o obvio — acha angulos unicos',
      'Energia contagiante em grupo',
      'Adaptavel a qualquer tipo de projeto',
    ],
    pontosFracos: [
      'Dificuldade em finalizar — sempre quer mudar',
      'Pode debater demais e executar de menos',
      'Se entedia com rotina e repeticao',
      'As vezes desrespeita processos estabelecidos',
    ],
    comoTrabalha: [
      'Precisa de variedade e estimulo constante',
      'Rende mais nas fases iniciais e conceituais',
      'Prefere ambientes informais e colaborativos',
      'Se motiva com liberdade criativa total',
    ],
    comoComunica: 'Entusiastico e provocador. Adora debater ideias. De espaco pra ele voar, mas ajude a aterrissar — precisa de alguem que canalize a energia.',
    fraseChave: '"Ta bom, mas e se a gente virasse isso de cabeca pra baixo?"',
  },

  // Diplomatas
  INFJ: {
    tipo: 'INFJ',
    nome: 'O Narrador',
    subtitulo: 'Transforma historias em experiencias emocionais',
    descricao: 'Entende o proposito profundo de cada projeto. Transforma historias em experiencias emocionais que conectam marcas a pessoas. Sua sensibilidade e seu superpoder na edicao e no conceito. Voce ve alem da superficie — entende o que o publico precisa sentir e constroi narrativas que ficam na memoria.',
    categoria: 'diplomatas',
    cor: '#14AE5C',
    icone: '📖',
    famosos: ['Hayao Miyazaki', 'Terrence Malick', 'Chloe Zhao', 'Andrei Tarkovsky'],
    pontosFortes: [
      'Sensibilidade narrativa excepcional',
      'Conecta a mensagem ao emocional do publico',
      'Profundidade conceitual rara',
      'Empatia que melhora o trabalho em equipe',
      'Consistencia e dedicacao silenciosa',
    ],
    pontosFracos: [
      'Perfeccionismo emocional — quer que "sinta certo"',
      'Pode levar criticas muito pessoalmente',
      'Dificuldade em se impor em debates acalorados',
      'Tende a absorver o estresse dos outros',
    ],
    comoTrabalha: [
      'Precisa de proposito claro no projeto',
      'Rende mais em ambientes calmos e focados',
      'Prefere profundidade a velocidade',
      'Se motiva com impacto emocional do trabalho',
    ],
    comoComunica: 'Gentil e profundo. Ouve antes de falar. Valorize suas contribuicoes — ele ve nuances que outros perdem. Feedback negativo com cuidado.',
    fraseChave: '"O que a gente quer que a pessoa sinta ao assistir isso?"',
  },
  INFP: {
    tipo: 'INFP',
    nome: 'O Poeta Visual',
    subtitulo: 'Cada frame carrega intencao e autenticidade',
    descricao: 'Cada frame e uma declaracao artistica. Busca autenticidade e beleza em tudo que produz. Pode demorar mais, mas o resultado carrega uma alma que nenhum template replica. Sua visao artistica unica e sua capacidade de encontrar beleza no inesperado fazem de voce o artista que eleva o padrao de tudo que toca.',
    categoria: 'diplomatas',
    cor: '#14AE5C',
    icone: '🎨',
    famosos: ['Wes Anderson', 'Sofia Coppola', 'Wong Kar-wai', 'Tim Burton'],
    pontosFortes: [
      'Estetica unica e reconhecivel',
      'Autenticidade artistica inabalavel',
      'Sensibilidade visual apurada',
      'Capacidade de criar atmosferas unicas',
      'Dedicacao quase obsessiva ao detalhe',
    ],
    pontosFracos: [
      'Dificuldade com prazos apertados',
      'Pode se isolar demais no processo criativo',
      'Resistencia a feedbacks que comprometam a visao',
      'Leva tempo pra se abrir com equipe nova',
    ],
    comoTrabalha: [
      'Precisa de liberdade artistica real',
      'Rende mais com tempo e sem pressao constante',
      'Prefere projetos que admira esteticamente',
      'Se motiva com reconhecimento da qualidade',
    ],
    comoComunica: 'Reservado mas profundo. Expressa mais pelo trabalho do que pelas palavras. De tempo e espaco — a melhor produção dele vem quando nao se sente pressionado.',
    fraseChave: '"Isso pode ficar lindo se a gente tiver paciencia."',
  },
  ENFJ: {
    tipo: 'ENFJ',
    nome: 'O Produtor Lider',
    subtitulo: 'A cola que mantem a equipe unida e motivada',
    descricao: 'A cola que mantem a equipe unida e motivada. Entende cada membro, alinha expectativas do cliente e garante que o projeto flua com harmonia. Sets com voce sao sets felizes. Sua habilidade natural de ler pessoas e criar ambientes de trabalho positivos faz de voce o profissional que todo projeto grande precisa.',
    categoria: 'diplomatas',
    cor: '#14AE5C',
    icone: '🤝',
    famosos: ['Oprah Winfrey', 'Steven Spielberg', 'Ron Howard', 'Ava DuVernay'],
    pontosFortes: [
      'Excelente em gerenciar pessoas e conflitos',
      'Comunica com clareza e empatia',
      'Cria ambientes de trabalho positivos',
      'Antecipa necessidades da equipe',
      'Ponte natural entre cliente e producao',
    ],
    pontosFracos: [
      'Pode priorizar harmonia sobre qualidade',
      'Dificuldade em dar feedback negativo',
      'Tende a assumir responsabilidades demais',
      'Pode se frustrar com conflitos nao resolvidos',
    ],
    comoTrabalha: [
      'Precisa de interacao e colaboracao',
      'Rende mais quando a equipe esta alinhada',
      'Prefere projetos com componente humano forte',
      'Se motiva com feedback positivo e reconhecimento',
    ],
    comoComunica: 'Caloroso e motivador. Celebre conquistas com ele. Seja transparente — ele percebe quando algo nao esta certo e prefere honestidade.',
    fraseChave: '"Como a gente pode fazer todo mundo brilhar nesse projeto?"',
  },
  ENFP: {
    tipo: 'ENFP',
    nome: 'O Criativo Livre',
    subtitulo: 'Energia contagiante e ideias que nao param',
    descricao: 'Ideias infinitas, energia contagiante e entusiasmo que eletriza qualquer brainstorm. Ve possibilidades onde outros veem limites. Seu maior desafio? Escolher qual ideia brilhante seguir. Sua capacidade de gerar entusiasmo e ver potencial em tudo faz de voce o catalisador que transforma projetos comuns em extraordinarios.',
    categoria: 'diplomatas',
    cor: '#14AE5C',
    icone: '⚡',
    famosos: ['Robin Williams', 'Pedro Almodovar', 'Baz Luhrmann', 'Greta Gerwig'],
    pontosFortes: [
      'Criatividade e entusiasmo inesgotaveis',
      'Conecta pessoas e ideias naturalmente',
      'Adaptavel a qualquer situacao',
      'Otimismo contagiante',
      'Excelente em vendas e pitching de ideias',
    ],
    pontosFracos: [
      'Dificuldade em manter foco em um projeto',
      'Pode prometer mais do que entrega',
      'Se entedia com detalhes e finalizacao',
      'Pode ignorar limites praticos por empolgacao',
    ],
    comoTrabalha: [
      'Precisa de variedade e estímulos novos',
      'Rende mais em fases criativas e de concepcao',
      'Prefere ambientes flexiveis e informais',
      'Se motiva com novidade e reconhecimento social',
    ],
    comoComunica: 'Expansivo e emocional. Adora compartilhar ideias. Canalize a energia — ajude a transformar entusiasmo em acao concreta.',
    fraseChave: '"Cara, tive uma ideia INCRIVEL agora!"',
  },

  // Sentinelas
  ISTJ: {
    tipo: 'ISTJ',
    nome: 'O Editor Cirurgico',
    subtitulo: 'Precisao, consistencia e entrega impecavel',
    descricao: 'Precisao, consistencia e entrega impecavel. Cada corte e calculado, cada transicao e intencional. Projetos nas suas maos saem no prazo e sem erro. A espinha dorsal de qualquer produtora. Sua confiabilidade e atencao meticulosa aos detalhes fazem de voce o profissional que garante que tudo saia como planejado.',
    categoria: 'sentinelas',
    cor: '#4A90D9',
    icone: '✂️',
    famosos: ['Walter Murch', 'Thelma Schoonmaker', 'Michael Kahn', 'Anne V. Coates'],
    pontosFortes: [
      'Confiabilidade absoluta em entregas',
      'Atencao meticulosa aos detalhes',
      'Consistencia de qualidade entre projetos',
      'Disciplina e organizacao naturais',
      'Excelente em processos e workflows',
    ],
    pontosFracos: [
      'Resistencia a mudancas de processo',
      'Pode ser rigido demais com regras',
      'Dificuldade com ambiguidade criativa',
      'Pode parecer inflexivel sob pressao',
    ],
    comoTrabalha: [
      'Precisa de processos claros e estaveis',
      'Rende mais com briefings detalhados',
      'Prefere um projeto de cada vez com foco total',
      'Se motiva com reconhecimento da confiabilidade',
    ],
    comoComunica: 'Factual e preciso. Prefere instrucoes claras e escritas. Respeite o processo dele — funciona porque e testado e comprovado.',
    fraseChave: '"Ta no prazo, ta no padrao, ta entregue."',
  },
  ISFJ: {
    tipo: 'ISFJ',
    nome: 'O Guardiao do Acervo',
    subtitulo: 'Memoria viva e cuidador dos processos',
    descricao: 'Memoria viva da produtora. Sabe onde esta cada arquivo, cada referencia, cada versao. Cuida dos processos e das pessoas com igual dedicacao. Sem voce, o caos reinaria. Sua atencao silenciosa e constante garante que nada se perca e que a equipe tenha tudo que precisa pra trabalhar.',
    categoria: 'sentinelas',
    cor: '#4A90D9',
    icone: '🗂️',
    famosos: ['Roger Deakins (suporte)', 'Edith Head', 'Sandy Powell', 'Emmanuel Lubezki'],
    pontosFortes: [
      'Organizacao e memoria impecaveis',
      'Cuidado genuino com a equipe',
      'Consistencia e lealdade',
      'Atencao a detalhes que outros ignoram',
      'Excelente em manter acervos e bibliotecas',
    ],
    pontosFracos: [
      'Dificuldade em dizer nao',
      'Pode se sobrecarregar cuidando dos outros',
      'Resistencia a mudancas bruscas',
      'Nao gosta de se promover ou pedir credito',
    ],
    comoTrabalha: [
      'Precisa de estabilidade e rotina',
      'Rende mais quando se sente valorizado',
      'Prefere trabalhar nos bastidores',
      'Se motiva com gratidao e reconhecimento pessoal',
    ],
    comoComunica: 'Gentil e prestativo. Sempre disposto a ajudar. Reconheca o trabalho invisivel dele — sem ele, nada funciona direito.',
    fraseChave: '"Ja separei tudo que voce vai precisar."',
  },
  ESTJ: {
    tipo: 'ESTJ',
    nome: 'O Gerente de Producao',
    subtitulo: 'Cronograma sagrado, entrega garantida',
    descricao: 'Cronograma e sagrado, briefing e lei. Organiza equipes, controla orcamentos e garante que cada entrega saia no padrao. Eficiencia e sua linguagem nativa. Sua capacidade de manter tudo nos trilhos e cobrar resultados sem perder o respeito da equipe faz de voce o gerente que todo projeto precisa.',
    categoria: 'sentinelas',
    cor: '#4A90D9',
    icone: '📋',
    famosos: ['Kevin Feige', 'Kathleen Kennedy', 'Jerry Bruckheimer', 'Scott Rudin'],
    pontosFortes: [
      'Gestao de equipe e recursos excepcional',
      'Foco em resultados e eficiencia',
      'Comunicacao clara e direta',
      'Controle de orcamento e prazos',
      'Lideranca pratica e acessivel',
    ],
    pontosFracos: [
      'Pode priorizar processo sobre criatividade',
      'Dificuldade em lidar com ambiguidade',
      'Pode ser visto como controlador',
      'Impaciente com quem nao segue o plano',
    ],
    comoTrabalha: [
      'Precisa de metas claras e mensuráveis',
      'Rende mais com equipe disciplinada',
      'Prefere hierarquia e papeis definidos',
      'Se motiva com resultados tangiveis',
    ],
    comoComunica: 'Direto e pratico. Gosta de status reports e atualizacoes. Traga numeros e fatos — ele decide rapido quando tem dados.',
    fraseChave: '"Qual o status? Ta no prazo?"',
  },
  ESFJ: {
    tipo: 'ESFJ',
    nome: 'O Atendimento Estrela',
    subtitulo: 'Ponte entre cliente e equipe com empatia',
    descricao: 'O cliente confia, a equipe respeita. Constroi pontes entre quem pede e quem executa com empatia e clareza. Transforma feedbacks dificeis em direcoes construtivas. Sua habilidade de traduzir expectativas do cliente em briefings claros e proteger a equipe ao mesmo tempo faz de voce insubstituivel.',
    categoria: 'sentinelas',
    cor: '#4A90D9',
    icone: '⭐',
    famosos: ['Shonda Rhimes', 'Ryan Murphy', 'Tyler Perry', 'Reese Witherspoon (produtora)'],
    pontosFortes: [
      'Relacionamento excepcional com clientes',
      'Traduz feedback em acoes claras',
      'Cria atmosfera positiva e colaborativa',
      'Memoria de preferencias e detalhes de clientes',
      'Resolve conflitos com diplomacia',
    ],
    pontosFracos: [
      'Pode evitar confrontos necessarios',
      'Tende a absorver estresse do cliente',
      'Dificuldade em manter limites profissionais',
      'Pode priorizar agradar sobre entregar certo',
    ],
    comoTrabalha: [
      'Precisa de interacao social e reconhecimento',
      'Rende mais quando a relacao com cliente e boa',
      'Prefere papeis de interface e mediacao',
      'Se motiva com feedback positivo do cliente',
    ],
    comoComunica: 'Caloroso e atento. Lembra de detalhes pessoais. Valorize o esforco de mediacao — ele absorve muito impacto que a equipe nem percebe.',
    fraseChave: '"Conversei com o cliente e consegui alinhar tudo."',
  },

  // Exploradores
  ISTP: {
    tipo: 'ISTP',
    nome: 'O Operador de Camera',
    subtitulo: 'Maos firmes, mente fria, dominio tecnico',
    descricao: 'Maos firmes, mente fria, reflexos rapidos. Domina equipamentos como extensao do corpo. No set, resolve problemas tecnicos em tempo real sem perder a compostura. Sua capacidade de manter a calma em situacoes de alta pressao e encontrar solucoes praticas na hora faz de voce o profissional que salva diarias inteiras.',
    categoria: 'exploradores',
    cor: '#FF8C00',
    icone: '📷',
    famosos: ['Roger Deakins', 'Emmanuel Lubezki', 'Hoyte van Hoytema', 'Bradford Young'],
    pontosFortes: [
      'Dominio tecnico de equipamentos',
      'Calma absoluta sob pressao',
      'Resolucao pratica de problemas no set',
      'Adaptavel a qualquer condicao de trabalho',
      'Aprendizado hands-on rapido',
    ],
    pontosFracos: [
      'Pode parecer distante ou desinteressado',
      'Comunicacao minima — assume que outros entendem',
      'Dificuldade com planejamento de longo prazo',
      'Prefere acao a reunioes — pode pular briefings',
    ],
    comoTrabalha: [
      'Precisa de desafios praticos e hands-on',
      'Rende mais resolvendo problemas reais no momento',
      'Prefere liberdade operacional',
      'Se motiva com dominio tecnico e resultados visiveis',
    ],
    comoComunica: 'Poucas palavras, muita acao. Mostra mais do que fala. Confie na competencia dele — se ele disse que resolve, resolve.',
    fraseChave: '"Deixa comigo, eu resolvo."',
  },
  ISFP: {
    tipo: 'ISFP',
    nome: 'O Artista Sensivel',
    subtitulo: 'Estetica apurada e sensibilidade unica',
    descricao: 'Estetica apurada e sensibilidade unica. Cada escolha de cor, luz e composicao carrega intencao. Trabalha no silencio e entrega obras que falam por si. Sua capacidade de criar beleza de forma instintiva e natural, sem forcar, faz do seu trabalho algo que as pessoas sentem antes de entender.',
    categoria: 'exploradores',
    cor: '#FF8C00',
    icone: '🖌️',
    famosos: ['Wes Anderson', 'Terrence Malick', 'Spike Jonze', 'Michel Gondry'],
    pontosFortes: [
      'Sensibilidade estetica natural',
      'Autenticidade artistica genuina',
      'Atencao a detalhes visuais sutil',
      'Versatilidade em estilos e linguagens',
      'Trabalho silencioso e consistente',
    ],
    pontosFracos: [
      'Pode se fechar sob criticas',
      'Dificuldade em verbalizar a visao artistica',
      'Tende a evitar conflitos mesmo quando necessarios',
      'Pode demorar por buscar perfeicao estetica',
    ],
    comoTrabalha: [
      'Precisa de ambiente tranquilo e sem pressao',
      'Rende mais quando admira o projeto esteticamente',
      'Prefere expressar pela obra, nao por palavras',
      'Se motiva com liberdade artistica e bom gosto',
    ],
    comoComunica: 'Sutil e sensivel. Expressa mais pelo trabalho. Crie um espaco seguro pra ele compartilhar — quando se abre, as insights sao preciosoas.',
    fraseChave: '"Isso tem que sentir bonito, nao so parecer."',
  },
  ESTP: {
    tipo: 'ESTP',
    nome: 'O Produtor de Campo',
    subtitulo: 'Resolve na hora, improvisa, faz acontecer',
    descricao: 'Resolve na hora, improvisa, faz acontecer. Choveu no set externo? Ja tem plano B, C e D. Energia inesgotavel e sangue frio em situacoes de pressao. O MVP de qualquer diaria. Sua capacidade de pensar rapido e agir sob pressao transforma problemas que paralisariam outros em solucoes criativas imediatas.',
    categoria: 'exploradores',
    cor: '#FF8C00',
    icone: '🏃',
    famosos: ['Guy Ritchie', 'Michael Bay', 'Zack Snyder', 'Robert Rodriguez'],
    pontosFortes: [
      'Resolucao instantanea de problemas',
      'Energia e resistencia incansaveis',
      'Sangue frio em situacoes de crise',
      'Networking natural — conhece todo mundo',
      'Pragmatismo puro — foca no que funciona',
    ],
    pontosFracos: [
      'Dificuldade com planejamento detalhado',
      'Pode ser impulsivo demais',
      'Se entedia com trabalho repetitivo',
      'Pode ignorar detalhes em favor da velocidade',
    ],
    comoTrabalha: [
      'Precisa de acao e dinamismo constante',
      'Rende mais em ambientes de alta pressao',
      'Prefere resolver fazendo, nao planejando',
      'Se motiva com adrenalina e resultados imediatos',
    ],
    comoComunica: 'Rapido e pragmatico. Vai direto ao ponto. Nao gasta tempo com teoria — fala de acao e resultado. Ideal pra emergencias.',
    fraseChave: '"Choveu? Beleza, vamos adaptar. Ja sei como."',
  },
  ESFP: {
    tipo: 'ESFP',
    nome: 'O Diretor de Elenco',
    subtitulo: 'Carisma que tira o melhor de qualquer pessoa',
    descricao: 'Carisma natural que coloca qualquer um a vontade na frente da camera. Entende pessoas como ninguem e tira performances genuinas de atores e entrevistados. A energia do set sobe quando voce chega. Sua presenca transforma o ambiente e sua capacidade de conectar com pessoas faz cada gravacao render mais.',
    categoria: 'exploradores',
    cor: '#FF8C00',
    icone: '🌟',
    famosos: ['Taika Waititi', 'Jordan Peele', 'Emerald Fennell', 'Barry Jenkins'],
    pontosFortes: [
      'Carisma e presenca natural',
      'Excelente em dirigir pessoas e performances',
      'Cria energia positiva no ambiente',
      'Le pessoas e situacoes intuitivamente',
      'Adaptavel e espontaneo',
    ],
    pontosFracos: [
      'Dificuldade com tarefas solitarias e repetitivas',
      'Pode perder foco em detalhes tecnicos',
      'Tende a evitar confrontos serios',
      'Pode subestimar complexidade de projetos',
    ],
    comoTrabalha: [
      'Precisa de interacao e energia do grupo',
      'Rende mais em sets e ambientes ao vivo',
      'Prefere improvisar a seguir script rigido',
      'Se motiva com a reacao das pessoas ao trabalho',
    ],
    comoComunica: 'Caloroso, expressivo e generoso. Celebra junto e motiva naturalmente. Aproveite o carisma dele pra energizar a equipe nos dias dificeis.',
    fraseChave: '"Relaxa, confia em mim. Vai ficar incrivel."',
  },
}

// 5th axis questions (Assertive vs Turbulent - from Big Five Neuroticism)
export const PERGUNTAS_IDENTIDADE = [
  { id: 21, texto: 'Fico tranquilo mesmo quando um projeto da errado — sei que da pra resolver', exemplo: 'Ex: O render travou na vespera da entrega. Voce fica calmo e busca alternativa ou bate o desespero?', polaridade: 1 as const },
  { id: 22, texto: 'Raramente me comparo com o trabalho dos outros da equipe', exemplo: 'Ex: Um colega ganhou elogio do cliente por um trabalho incrivel. Voce fica feliz por ele ou comeca a questionar o seu proprio trabalho?', polaridade: 1 as const },
  { id: 23, texto: 'Confio nas minhas decisoes criativas sem ficar revisando depois', exemplo: 'Ex: Voce exportou o video final. Depois fica assistindo em loop procurando erros ou segue pro proximo projeto tranquilo?', polaridade: 1 as const },
]
